export const BASE_URL = "https://slldm.com";
// export const BASE_URL = "http://192.168.1.5:8000"
export const initialState = {};

export const LOGIN_VENDOR = "LOGIN_VENDOR";
export const LOGIN_VENDOR_SUCCESS = "LOGIN_VENDOR_SUCCESS";
export const LOGIN_VENDOR_FAILURE = "LOGIN_VENDOR_FAILURE";
export const LOGIN_VENDOR_LOGOUT = "LOGIN_VENDOR_LOGOUT";
export const LOGIN_VENDOR_CHANGE_PASSWORD = "LOGIN_VENDOR_CHANGE_PASSWORD";
export const LOGIN_VENDOR_VIEW_PROFILE = "LOGIN_VENDOR_VIEW_PROFILE";

export const GET_ALL_TASKS = "GET_ALL_TASKS";
export const VIEW_TASK = "VIEW_TASK";
export const UPDATE_TASK = "UPDATE_TASK,";

export const GET_ALL_SITES = "GET_ALL_SITES";
export const VIEW_SITE = "VIEW_SITE";
export const SEARCH_SITE = "SEARCH_SITE";
export const SET_SITES_COUNT = "SET_SITES_COUNT"

export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const VIEW_PROJECT = "VIEW_PROJECT";
export const SEARCH_PROJECT = "SEARCH_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const COUNT_PROJECTS = "COUNT_PROJECTS";
export const CHANGE_PROJECT_STATUS = "CHANGE_PROJECT_STATUS";

export const GET_ALL_INVENTORY = "GET_ALL_INVENTORY";
export const VIEW_INVENTORY = "VIEW_INVENTORY";
export const UPDATE_INVENTORY = "UPDATE_INVENTORY";
export const SEARCH_INVENTORY = "SEARCH_INVENTORY";
export const COUNT_INVENTORY = "COUNT_INVENTORY";

export const VIEW_PAYMENT = "VIEW_PAYMENT";
export const SEARCH_PAYMENT = "SEARCH_PAYMENT";
export const UPDATE_PAYMENT = "UPDATE_PAYMENT";
export const DELETE_PAYMENT = "DELETE_PAYMENT";
export const COUNT_PAYMENTS = "COUNT_PAYMENTS";

// Set all constants here including assets, texts,etc
