export const BASE_URL = "https://slldm.com";
//export const BASE_URL = "http://192.168.1.5:8000"
//export const BASE_URL = "https://solarcrm.dashandots.tech";
export const initialState = {};

export const LOGIN_VENDOR = "LOGIN_VENDOR";
export const LOGIN_VENDOR_SUCCESS = "LOGIN_VENDOR_SUCCESS";
export const LOGIN_VENDOR_FAILURE = "LOGIN_VENDOR_FAILURE";
export const LOGIN_VENDOR_LOGOUT = "LOGIN_VENDOR_LOGOUT";
export const LOGIN_VENDOR_CHANGE_PASSWORD = "LOGIN_VENDOR_CHANGE_PASSWORD";
export const LOGIN_VENDOR_VIEW_PROFILE = "LOGIN_VENDOR_VIEW_PROFILE";

export const GET_ALL_TASKS = "GET_ALL_TASKS";
export const VIEW_TASK = "VIEW_TASK";
export const UPDATE_TASK = "UPDATE_TASK,";

export const GET_ALL_SITES = "GET_ALL_SITES";
export const VIEW_SITE = "VIEW_SITE";
export const SEARCH_SITE = "SEARCH_SITE";
export const SET_SITES_COUNT = "SET_SITES_COUNT";

export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const VIEW_PROJECT = "VIEW_PROJECT";
export const SEARCH_PROJECT = "SEARCH_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const COUNT_PROJECTS = "COUNT_PROJECTS";
export const CHANGE_PROJECT_STATUS = "CHANGE_PROJECT_STATUS";

export const GET_ALL_INVENTORY = "GET_ALL_INVENTORY";
export const GET_TODAY_INVENTORY = "GET_TODAY_INVENTORY";
export const SET_TOTAL_INVENTORY_VALUE = "SET_TOTAL_INVENTORY_VALUE";
export const VIEW_INVENTORY = "VIEW_INVENTORY";
export const UPDATE_INVENTORY = "UPDATE_INVENTORY";
export const SEARCH_INVENTORY = "SEARCH_INVENTORY";
export const COUNT_INVENTORY = "COUNT_INVENTORY";
export const GET_TOTAL_RECEIVED_INVENTORY = "GET_TOTAL_RECEIVED_INVENTORY";
export const GET_IN_STOCK = "GET_IN_STOCK";
export const GET_CONSUMED = "GET_CONSUMED";

export const VIEW_PAYMENT = "VIEW_PAYMENT";
export const SEARCH_PAYMENT = "SEARCH_PAYMENT";
export const UPDATE_PAYMENT = "UPDATE_PAYMENT";
export const DELETE_PAYMENT = "DELETE_PAYMENT";
export const COUNT_PAYMENTS = "COUNT_PAYMENTS";

// Set all constants here including assets, texts,etc
export const GET_PENDING_STREETLIGHTS = "GET_PENDING_STREETLIGHTS";
export const TOTAL_PENDING_STREETLIGHT = "SET_TOTAL_PENDING_STREETLIGHT";
export const GET_SURVEYED_STREETLIGHTS = "GET_SURVEYED_STREETLIGHTS";
export const TOTAL_SURVEYED_STREETLIGHTS = "TOTAL_SURVEYED_STREETLIGHTS";
export const GET_INSTALLED_STREETLIGHTS = "GET_INSTALLED_STREETLIGHTS";
export const GET_APPROVED_STREETLIGHTS = "GET_APPROVED_STREETLIGHTS";
export const GET_REJECTED_STREETLIGHTS = "GET_REJECTED_STREETLIGHTS";
export const TOTAL_INSTALLED_STREETLIGHTS = "TOTAL_INSTALLED_STREETLIGHTS";
export const GET_VIEW_STREETLIGHTS = "GET_VIEW_STREETLIGHTS";
export const SET_POLE_NUMBER = "SET_POLE_NUMBER";
export const SET_BENEFICIARY_NAME = "SET_BENEFICIARY_NAME";
export const SET_LOCATION_REMARKS = "SET_LOCATION_REMARKS";
export const SET_BENEFICIARY_CONTACT = "SET_BENEFICIARY_CONTACT";
