name: "Build Android App"
run-name: ${{ github.actor }} is learning build Android App using Github Actions
on:
  push:
    branches:
      - rohit
  pull_request:
    branches:
      - rohit
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "20"
          distribution: "adopt"
          cache: "gradle"

      - name: Change wrapper permissions
        run: chmod +x ./android/gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Run Yarn Install
        run: |
          npm install

      - name: Build App
        run: |
          cd ./android
          ./gradlew bundleRelease

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./android/app/outputs/bundle/release/app-release.aab
          retention-days: 3